// <auto-generated />
using System;
using BlazeLock.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazeLock.API.Migrations
{
    [DbContext(typeof(BlazeLockContext))]
    [Migration("20251221110348_EntreeCascadeOnFolderDelete")]
    partial class EntreeCascadeOnFolderDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazeLock.API.Models.Coffre", b =>
                {
                    b.Property<Guid>("IdCoffre")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_coffre");

                    b.Property<byte[]>("HashMasterkey")
                        .IsRequired()
                        .HasColumnType("varbinary(50)")
                        .HasColumnName("hash_masterkey");

                    b.Property<Guid>("IdUtilisateur")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("libelle");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(50)")
                        .HasColumnName("salt");

                    b.HasKey("IdCoffre");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("Coffre", (string)null);
                });

            modelBuilder.Entity("BlazeLock.API.Models.Dossier", b =>
                {
                    b.Property<Guid>("IdDossier")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_dossier");

                    b.Property<Guid>("IdCoffre")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_coffre");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("libelle");

                    b.HasKey("IdDossier");

                    b.HasIndex("IdCoffre");

                    b.ToTable("Dossier", (string)null);
                });

            modelBuilder.Entity("BlazeLock.API.Models.Entree", b =>
                {
                    b.Property<Guid>("IdEntree")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_entree");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime")
                        .HasColumnName("date_creation");

                    b.Property<Guid>("IdDossier")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_dossier");

                    b.HasKey("IdEntree");

                    b.HasIndex("IdDossier");

                    b.ToTable("Entree", (string)null);
                });

            modelBuilder.Entity("BlazeLock.API.Models.HistoriqueEntree", b =>
                {
                    b.Property<Guid>("IdHistorique")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_historique");

                    b.Property<byte[]>("Commentaire")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varbinary(50)")
                        .HasColumnName("commentaire");

                    b.Property<byte[]>("CommentaireTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varbinary(50)")
                        .HasColumnName("commentaire_tag");

                    b.Property<byte[]>("CommentaireVi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varbinary(50)")
                        .HasColumnName("commentaire_vi");

                    b.Property<DateTime>("DateUpdate")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("date_update");

                    b.Property<Guid>("IdEntree")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_entree");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("libelle");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varbinary(50)")
                        .HasColumnName("password");

                    b.Property<byte[]>("PasswordTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varbinary(50)")
                        .HasColumnName("password_tag");

                    b.Property<byte[]>("PasswordVi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varbinary(50)")
                        .HasColumnName("password_vi");

                    b.Property<byte[]>("Url")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varbinary(50)")
                        .HasColumnName("url");

                    b.Property<byte[]>("UrlTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varbinary(50)")
                        .HasColumnName("url_tag");

                    b.Property<byte[]>("UrlVi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varbinary(50)")
                        .HasColumnName("url_vi");

                    b.Property<byte[]>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varbinary(50)")
                        .HasColumnName("username");

                    b.Property<byte[]>("UsernameTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varbinary(50)")
                        .HasColumnName("username_tag");

                    b.Property<byte[]>("UsernameVi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varbinary(50)")
                        .HasColumnName("username_vi");

                    b.HasKey("IdHistorique");

                    b.HasIndex("IdEntree");

                    b.ToTable("Historique_entree", (string)null);
                });

            modelBuilder.Entity("BlazeLock.API.Models.Log", b =>
                {
                    b.Property<Guid>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_log");

                    b.Property<Guid>("IdCoffre")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_coffre");

                    b.Property<Guid>("IdUtilisateur")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texte")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("texte");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp_");

                    b.HasKey("IdLog");

                    b.HasIndex("IdCoffre");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("Log", (string)null);
                });

            modelBuilder.Entity("BlazeLock.API.Models.Partage", b =>
                {
                    b.Property<Guid>("IdUtilisateur")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_utilisateur");

                    b.Property<Guid>("IdCoffre")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_coffre");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("isAdmin");

                    b.HasKey("IdUtilisateur", "IdCoffre");

                    b.HasIndex("IdCoffre");

                    b.ToTable("Partage", (string)null);
                });

            modelBuilder.Entity("BlazeLock.API.Models.Utilisateur", b =>
                {
                    b.Property<Guid>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdUtilisateur");

                    b.ToTable("Utilisateur", (string)null);
                });

            modelBuilder.Entity("BlazeLock.API.Models.Coffre", b =>
                {
                    b.HasOne("BlazeLock.API.Models.Utilisateur", "Utilisateur")
                        .WithMany("Coffres")
                        .HasForeignKey("IdUtilisateur")
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BlazeLock.API.Models.Dossier", b =>
                {
                    b.HasOne("BlazeLock.API.Models.Coffre", "Coffre")
                        .WithMany("Dossiers")
                        .HasForeignKey("IdCoffre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coffre");
                });

            modelBuilder.Entity("BlazeLock.API.Models.Entree", b =>
                {
                    b.HasOne("BlazeLock.API.Models.Dossier", "Dossier")
                        .WithMany("Entrees")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("BlazeLock.API.Models.HistoriqueEntree", b =>
                {
                    b.HasOne("BlazeLock.API.Models.Entree", "Entree")
                        .WithMany("HistoriqueEntrees")
                        .HasForeignKey("IdEntree")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entree");
                });

            modelBuilder.Entity("BlazeLock.API.Models.Log", b =>
                {
                    b.HasOne("BlazeLock.API.Models.Coffre", "Coffre")
                        .WithMany("Logs")
                        .HasForeignKey("IdCoffre")
                        .IsRequired();

                    b.HasOne("BlazeLock.API.Models.Utilisateur", "Utilisateur")
                        .WithMany("Logs")
                        .HasForeignKey("IdUtilisateur")
                        .IsRequired();

                    b.Navigation("Coffre");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BlazeLock.API.Models.Partage", b =>
                {
                    b.HasOne("BlazeLock.API.Models.Coffre", "Coffre")
                        .WithMany("Partages")
                        .HasForeignKey("IdCoffre")
                        .IsRequired();

                    b.HasOne("BlazeLock.API.Models.Utilisateur", "Utilisateur")
                        .WithMany("Partages")
                        .HasForeignKey("IdUtilisateur")
                        .IsRequired();

                    b.Navigation("Coffre");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BlazeLock.API.Models.Coffre", b =>
                {
                    b.Navigation("Dossiers");

                    b.Navigation("Logs");

                    b.Navigation("Partages");
                });

            modelBuilder.Entity("BlazeLock.API.Models.Dossier", b =>
                {
                    b.Navigation("Entrees");
                });

            modelBuilder.Entity("BlazeLock.API.Models.Entree", b =>
                {
                    b.Navigation("HistoriqueEntrees");
                });

            modelBuilder.Entity("BlazeLock.API.Models.Utilisateur", b =>
                {
                    b.Navigation("Coffres");

                    b.Navigation("Logs");

                    b.Navigation("Partages");
                });
#pragma warning restore 612, 618
        }
    }
}
