// <auto-generated />
using System;
using BlazeLock.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazeLock.API.Migrations
{
    [DbContext(typeof(BlazeLockContext))]
    partial class BlazeLockContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazeLock.API.Models.Coffre", b =>
                {
                    b.Property<Guid>("IdCoffre")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_coffre");

                    b.Property<string>("HashMasterkey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("hash_masterkey");

                    b.Property<Guid>("IdUtilisateur")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Libelle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("libelle");

                    b.Property<string>("Salt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("salt");

                    b.HasKey("IdCoffre")
                        .HasName("PK__Coffre__47508D12F46D3B31");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("Coffre", (string)null);
                });

            modelBuilder.Entity("BlazeLock.API.Models.Dossier", b =>
                {
                    b.Property<Guid>("IdDossier")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_dossier");

                    b.Property<Guid?>("IdDossier1")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_dossier_1");

                    b.Property<string>("Libelle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("libelle");

                    b.HasKey("IdDossier")
                        .HasName("PK__Dossier__4484C37EEDA5F640");

                    b.HasIndex("IdDossier1");

                    b.ToTable("Dossier", (string)null);
                });

            modelBuilder.Entity("BlazeLock.API.Models.Entree", b =>
                {
                    b.Property<Guid>("IdEntree")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_entree");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime")
                        .HasColumnName("date_creation");

                    b.HasKey("IdEntree")
                        .HasName("PK__Entree__B8AEB9F2EB302244");

                    b.ToTable("Entree", (string)null);
                });

            modelBuilder.Entity("BlazeLock.API.Models.HistoriqueEntree", b =>
                {
                    b.Property<Guid>("IdHistorique")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_historique");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("commentaire");

                    b.Property<string>("CommentaireTag")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("commentaire_tag");

                    b.Property<string>("CommentaireVi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("commentaire_vi");

                    b.Property<string>("DateUpdate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("date_update");

                    b.Property<Guid>("IdEntree")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_entree");

                    b.Property<string>("Libelle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("libelle");

                    b.Property<string>("LibelleTag")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("libelle_tag");

                    b.Property<string>("LibelleVi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("libelle_vi");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("password");

                    b.Property<string>("PasswordTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("password_tag");

                    b.Property<string>("PasswordVi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("password_vi");

                    b.Property<string>("Url")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("url");

                    b.Property<string>("UrlTag")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("url_tag");

                    b.Property<string>("UrlVi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("url_vi");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.Property<string>("UsernameTag")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username_tag");

                    b.Property<string>("UsernameVi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username_vi");

                    b.HasKey("IdHistorique")
                        .HasName("PK__Historiq__33F46ECB49A6FF51");

                    b.HasIndex("IdEntree");

                    b.ToTable("Historique_entree", (string)null);
                });

            modelBuilder.Entity("BlazeLock.API.Models.Log", b =>
                {
                    b.Property<Guid>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_log");

                    b.Property<Guid>("IdCoffre")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_coffre");

                    b.Property<string>("Texte")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("texte");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp_");

                    b.HasKey("IdLog")
                        .HasName("PK__Log__6CC851FE0CAB883A");

                    b.HasIndex("IdCoffre");

                    b.ToTable("Log", (string)null);
                });

            modelBuilder.Entity("BlazeLock.API.Models.Partage", b =>
                {
                    b.Property<Guid>("IdUtilisateur")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_utilisateur");

                    b.Property<Guid>("IdCoffre")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_coffre");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("isAdmin");

                    b.HasKey("IdUtilisateur", "IdCoffre")
                        .HasName("PK__Partage__2E3AAD6978ABB493");

                    b.HasIndex("IdCoffre");

                    b.ToTable("Partage", (string)null);
                });

            modelBuilder.Entity("BlazeLock.API.Models.Utilisateur", b =>
                {
                    b.Property<Guid>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_utilisateur");

                    b.HasKey("IdUtilisateur")
                        .HasName("PK__Utilisat__1A4FA5B84005D655");

                    b.ToTable("Utilisateur", (string)null);
                });

            modelBuilder.Entity("Organiser", b =>
                {
                    b.Property<Guid>("IdCoffre")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_coffre");

                    b.Property<Guid>("IdDossier")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_dossier");

                    b.HasKey("IdCoffre", "IdDossier")
                        .HasName("PK__Organise__B318C125E234F68B");

                    b.HasIndex("IdDossier");

                    b.ToTable("Organiser", (string)null);
                });

            modelBuilder.Entity("Stocker", b =>
                {
                    b.Property<Guid>("IdDossier")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_dossier");

                    b.Property<Guid>("IdEntree")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_entree");

                    b.HasKey("IdDossier", "IdEntree")
                        .HasName("PK__Stocker__7F0E28E12110E1D5");

                    b.HasIndex("IdEntree");

                    b.ToTable("Stocker", (string)null);
                });

            modelBuilder.Entity("BlazeLock.API.Models.Coffre", b =>
                {
                    b.HasOne("BlazeLock.API.Models.Utilisateur", "IdUtilisateurNavigation")
                        .WithMany("Coffres")
                        .HasForeignKey("IdUtilisateur")
                        .IsRequired()
                        .HasConstraintName("FK__Coffre__id_utili__398D8EEE");

                    b.Navigation("IdUtilisateurNavigation");
                });

            modelBuilder.Entity("BlazeLock.API.Models.Dossier", b =>
                {
                    b.HasOne("BlazeLock.API.Models.Dossier", "IdDossier1Navigation")
                        .WithMany("InverseIdDossier1Navigation")
                        .HasForeignKey("IdDossier1")
                        .HasConstraintName("FK__Dossier__Id_doss__3C69FB99");

                    b.Navigation("IdDossier1Navigation");
                });

            modelBuilder.Entity("BlazeLock.API.Models.HistoriqueEntree", b =>
                {
                    b.HasOne("BlazeLock.API.Models.Entree", "IdEntreeNavigation")
                        .WithMany("HistoriqueEntrees")
                        .HasForeignKey("IdEntree")
                        .IsRequired()
                        .HasConstraintName("FK__Historiqu__id_en__412EB0B6");

                    b.Navigation("IdEntreeNavigation");
                });

            modelBuilder.Entity("BlazeLock.API.Models.Log", b =>
                {
                    b.HasOne("BlazeLock.API.Models.Coffre", "IdCoffreNavigation")
                        .WithMany("Logs")
                        .HasForeignKey("IdCoffre")
                        .IsRequired()
                        .HasConstraintName("FK__Log__id_coffre__440B1D61");

                    b.Navigation("IdCoffreNavigation");
                });

            modelBuilder.Entity("BlazeLock.API.Models.Partage", b =>
                {
                    b.HasOne("BlazeLock.API.Models.Coffre", "IdCoffreNavigation")
                        .WithMany("Partages")
                        .HasForeignKey("IdCoffre")
                        .IsRequired()
                        .HasConstraintName("FK__Partage__id_coff__47DBAE45");

                    b.HasOne("BlazeLock.API.Models.Utilisateur", "IdUtilisateurNavigation")
                        .WithMany("Partages")
                        .HasForeignKey("IdUtilisateur")
                        .IsRequired()
                        .HasConstraintName("FK__Partage__id_util__46E78A0C");

                    b.Navigation("IdCoffreNavigation");

                    b.Navigation("IdUtilisateurNavigation");
                });

            modelBuilder.Entity("Organiser", b =>
                {
                    b.HasOne("BlazeLock.API.Models.Coffre", null)
                        .WithMany()
                        .HasForeignKey("IdCoffre")
                        .IsRequired()
                        .HasConstraintName("FK__Organiser__id_co__4AB81AF0");

                    b.HasOne("BlazeLock.API.Models.Dossier", null)
                        .WithMany()
                        .HasForeignKey("IdDossier")
                        .IsRequired()
                        .HasConstraintName("FK__Organiser__Id_do__4BAC3F29");
                });

            modelBuilder.Entity("Stocker", b =>
                {
                    b.HasOne("BlazeLock.API.Models.Dossier", null)
                        .WithMany()
                        .HasForeignKey("IdDossier")
                        .IsRequired()
                        .HasConstraintName("FK__Stocker__Id_doss__4E88ABD4");

                    b.HasOne("BlazeLock.API.Models.Entree", null)
                        .WithMany()
                        .HasForeignKey("IdEntree")
                        .IsRequired()
                        .HasConstraintName("FK__Stocker__id_entr__4F7CD00D");
                });

            modelBuilder.Entity("BlazeLock.API.Models.Coffre", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Partages");
                });

            modelBuilder.Entity("BlazeLock.API.Models.Dossier", b =>
                {
                    b.Navigation("InverseIdDossier1Navigation");
                });

            modelBuilder.Entity("BlazeLock.API.Models.Entree", b =>
                {
                    b.Navigation("HistoriqueEntrees");
                });

            modelBuilder.Entity("BlazeLock.API.Models.Utilisateur", b =>
                {
                    b.Navigation("Coffres");

                    b.Navigation("Partages");
                });
#pragma warning restore 612, 618
        }
    }
}
